In [35]:
import numpy as np

In [141]:
def initPopBinary(npop,clen):
    pop = np.random.randint(0,2,(npop, clen))
    
    return pop

In [207]:
pop = initPopBinary(20,5)
pop

array([[0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1],
       [1, 1, 0, 1, 1]])

In [214]:
def oneMaxI(chromosome): 
    chromoseomFitness = np.sum(chromosome,axis=0)
    return chromoseomFitness

In [215]:
fitness=oneMaxI(pop)
fitness

array([10, 10, 11,  9, 14])

In [216]:
def oneMaxP(pop, npop):
    popFit = np.zeros(npop)
    for i in range(npop):
        popFit[i] = oneMaxI(pop[i])
    return popFit

In [217]:
pop = np.array([
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 1, 1]])
popFit = oneMaxP(pop,20) 
popFit

array([1., 2., 3., 2., 3., 3., 2., 2., 2., 5., 2., 3., 3., 3., 3., 1., 4.,
       4., 3., 3.])

In [218]:
def selectionProb(popFit): 
# Use this function to calculate the selection probability for each individual in the population
    # popFit: a one dimension array of the population size (npop) including the fitness value 
    # for all the individuals in the population
    #probs =  np.array(popFit, dtype='f')/sum(popFit)
    totalFitness = sum(popFit)
    probs = [i/totalFitness for i in popFit]
    return probs # probs: a one dimension array representing the selection probabilities for every individual in the population

In [190]:
prob = selectionProb(popFit)
prob

[0.018518518518518517,
 0.037037037037037035,
 0.05555555555555555,
 0.037037037037037035,
 0.05555555555555555,
 0.05555555555555555,
 0.037037037037037035,
 0.037037037037037035,
 0.037037037037037035,
 0.09259259259259259,
 0.037037037037037035,
 0.05555555555555555,
 0.05555555555555555,
 0.05555555555555555,
 0.05555555555555555,
 0.018518518518518517,
 0.07407407407407407,
 0.07407407407407407,
 0.05555555555555555,
 0.05555555555555555]

In [191]:
def cumProb(prob): 
    # Use this function to calculate the cummulative probabilities for each individual in the population, 
        # ex: probs= [0.1667, 0.5, 0.0833, 0.25],
        # cprob =[0.1667, 0.6667, 0.75, 1].
        # probs: a one dimension array representing the selection probabilities for every individual in the population
    cprob = np.zeros_like(prob)
    cprob[0] = prob[0]
    for i in range(1,len(prob)):
        cprob[i] = cprob[i-1] + prob[i]
        
    return cprob #cprob a vector representing cummlative probability for each individual in the population

In [192]:
cprobb = cumProb(prob)
cprobb

array([0.01851852, 0.05555556, 0.11111111, 0.14814815, 0.2037037 ,
       0.25925926, 0.2962963 , 0.33333333, 0.37037037, 0.46296296,
       0.5       , 0.55555556, 0.61111111, 0.66666667, 0.72222222,
       0.74074074, 0.81481481, 0.88888889, 0.94444444, 1.        ])

In [219]:
def rouletteWheel(cprob): 
# Use this function to implement the roulette wheel selection, to select a single parent index
    #cprob: cummlative probability for each individual in the population
    r = np.random.random()
    for i in range(len(cprob)):
        if r <= cprob[i]:
            indx = i
            return indx
        
    # indx: a value represents the index of the selected parent

In [220]:
indx = rouletteWheel(cprob)
indx
 

11

In [223]:
def rouletteSelect(cprob,pop): 
# Use this function to return 2 selected parents, 
    #hint: you will use the roulette_wheel function here
    #cprob: a vector representing cummlative probability for each individual in the population
    #pop: chromosomes population (2D array (npop X clen)
    twoParents = np.zeros((2,np.size(pop,1)))
    for i in range(2):
        indx = rouletteWheel(cprob)
        twoParents[i,:] = pop[indx,:] 
    return twoParents 
    #twoParents: a (2 X clen) matrix

In [224]:
twoParents = rouletteSelect(cprob,pop)
twoParents

array([[1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1.],
       [1., 0., 1., 1., 0.],
       [1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 1.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 0., 1.],
       [1., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0.],
       [0., 1., 1., 0., 1.],
       [1., 1., 1., 0., 1.],
       [0., 1., 1., 0., 1.],
       [1., 1., 1., 0., 0.],
       [0., 1., 1., 0., 1.],
       [1., 1., 1., 0., 1.]])

In [226]:
import random

def rouletteWheelSelection(pop, popFit, npop):
    """
    Selects the best-fitted individuals for the next population using Roulette Wheel selection.
    Takes the fitness of each individual and generates the probabilities of it.
    The probability of being selected is proportional to the relative fitness of the individual.
    Returns a new population of npop chromosomes selected using Roulette Wheel selection.
    """
    # Compute the cumulative fitness of the population
    cum_fitness = [sum(popFit[:i+1]) for i in range(len(popFit))]
    
    # Compute the total fitness of the population
    total_fitness = cum_fitness[-1]
    
    # Compute the probability of selecting each individual based on its fitness
    probabilities = [f / total_fitness for f in cum_fitness]
    
    # Select npop individuals using Roulette Wheel selection
    new_pop = []
    for i in range(npop):
        r = random.random()
        for j in range(len(probabilities)):
            if r < probabilities[j]:
                new_pop.append(pop[j])
                break
    
    return new_pop

In [229]:
# Use Roulette Wheel selection to select the best-fitted individuals for the next population
new_pop = rouletteWheelSelection(pop, popFit, 20)
new_pop

[array([0, 1, 1, 0, 1]),
 array([1, 0, 1, 1, 0]),
 array([1, 0, 1, 1, 0]),
 array([1, 1, 0, 0, 1]),
 array([0, 1, 1, 0, 1]),
 array([1, 1, 1, 1, 0]),
 array([0, 1, 1, 0, 1]),
 array([0, 0, 0, 1, 1]),
 array([0, 1, 1, 0, 1]),
 array([1, 0, 0, 1, 1]),
 array([1, 0, 1, 1, 0]),
 array([1, 1, 1, 1, 1]),
 array([1, 0, 0, 1, 1]),
 array([1, 1, 1, 0, 1]),
 array([1, 1, 1, 1, 0]),
 array([1, 0, 0, 1, 1]),
 array([0, 1, 1, 0, 1]),
 array([0, 0, 0, 1, 1]),
 array([0, 1, 1, 0, 1]),
 array([1, 0, 0, 1, 1])]

In [256]:
import numpy as np

def findBestIndividuals(pop, popFit):
    """
    Finds the two best individuals by fitness in a population represented as a list of individuals and their corresponding fitness values.
    Returns a tuple containing the two best individuals found.
    """
    
    # Find the indices of the two best fitness values in the list
    best_indices = np.argsort(popFit)[-2:]
    
    # Set the first best individual to the one with the best fitness value
    bestIndividual1 = pop[best_indices[-1]]
    
    # Set the second best individual to the one with the second best fitness value
    bestIndividual2 = pop[best_indices[-2]]
    
    return (bestIndividual1, bestIndividual2)

In [258]:

# Find the two best individuals by fitness in the population
bestIndividuals = findBestIndividuals(pop, popFit)

# Print the two best individuals
bestIndividuals

(array([1, 1, 1, 1, 1]), array([1, 1, 1, 1, 0]))

In [259]:
def binCross(twoParents, pcross, clen):
    """
    Performs binary crossover on two parent chromosomes represented as strings of binary digits.
    The crossover point is randomly selected with a probability of pcross.
    The crossover point is chosen such that at least one bit from each parent is included in the offspring.
    The length of the chromosomes is specified by clen.
    Returns a string representing the offspring chromosome.
    """
    parent1, parent2 = twoParents
    
    # Check if crossover should be performed
    if random.random() > pcross:
        return parent1
    
    # Select a crossover point
    crossoverPoint = random.randint(1, clen-1)
    
    # Create the offspring chromosome
    offspring = parent1[:crossoverPoint] + parent2[crossoverPoint:]
    
    return offspring

In [267]:
# Example parent chromosomes represented as strings of binary digits
parent1 = '1,1, 1, 1, 1'
parent2 = '1, 1, 1, 1, 0'

# Perform binary crossover on the parents
offspring = binCross((parent1, parent2), 0.6, len(parent1))

# Print the offspring chromosome
print(offspring)

1,1, 1, 1, 1


In [268]:
def bitFlipMutation(individual, pMut=0.05):
    """
    Performs bit-flip mutation on an individual chromosome represented as a list or string.
    The mutation probability is pMut (default 0.05).
    Returns a mutated version of the individual.
    """
    # Convert the individual to a list if it is a string
    if isinstance(individual, str):
        individual = list(individual)
    
    # Perform bit-flip mutation
    for i in range(len(individual)):
        if random.random() < pMut:
            individual[i] = '0' if individual[i] == '1' else '1'
    
    # Convert the individual back to a string if it was originally a string
    if isinstance(individual, str):
        individual = ''.join(individual)
    
    return individual

In [269]:
# Example individual chromosome represented as a string of binary digits
individual = 1, 1, 1, 1, 0

# Perform bit-flip mutation on the individual
mutatedIndividual = bitFlipMutation(individual, 0.05)

# Print the mutated individual chromosome
print(mutatedIndividual)

(1, 1, 1, 1, 0)


In [278]:
import random
import numpy as np

def genetic_algorithm(pop_size, num_generations, chrom_length, p_cross, p_mut, random_seed=None):
    """
    Performs a genetic algorithm on a population of individuals.
    Returns the final population, a vector containing the history of the highest fitness in the population at each generation, and the average fitness value.
    """
    if random_seed is not None:
        np.random.seed(random_seed)
        random.seed(random_seed)
    
    # Initialize the population with random binary strings
    population = [list(np.random.randint(2, size=chrom_length)) for i in range(pop_size)]
    
    # Initialize the history of the best and average fitness values
    best_hist = []
    avg_hist = []
    
    # Evaluate the initial population
    fitness_values = [fitness(individual) for individual in population]
    best_fitness = max(fitness_values)
    best_hist.append(best_fitness)
    avg_hist.append(np.mean(fitness_values))
    
    # Perform the specified number of generations
    for generation in range(num_generations):
        # Select parents for crossover using tournament selection
        parents = []
        for i in range(pop_size):
            # Select two individuals at random for the tournament
            tournament = random.sample(range(pop_size), 2)
            
            # Select the fitter individual as the parent
            if fitness_values[tournament[0]] > fitness_values[tournament[1]]:
                parents.append(population[tournament[0]])
            else:
                parents.append(population[tournament[1]])
        
        # Perform one-point crossover on the parents to create offspring
        offspring = []
        for i in range(pop_size):
            # Select two parents at random for crossover
            crossover_parents = random.sample(range(pop_size), 2)
            
            # Perform crossover with probability p_cross
            if random.random() < p_cross:
                crossover_point = random.randint(1, chrom_length-1)
                offspring1 = parents[crossover_parents[0]][:crossover_point] + parents[crossover_parents[1]][crossover_point:]
                offspring2 = parents[crossover_parents[1]][:crossover_point] + parents[crossover_parents[0]][crossover_point:]
            else:
                offspring1 = parents[crossover_parents[0]]
                offspring2 = parents[crossover_parents[1]]
            
            # Add the offspring to the list
            offspring.append(offspring1)
            offspring.append(offspring2)
        
        # Perform bit-flip mutation on the offspring with probability p_mut
        for i in range(len(offspring)):
            for j in range(chrom_length):
                if random.random() < p_mut:
                    offspring[i][j] = 1 - offspring[i][j]
        
        # Combine the old population and the offspring
        combined_population = population + offspring
        
        # Evaluate the combined population
        combined_fitness_values = [fitness(individual) for individual in combined_population]
        
        # Sort the combined population by fitness
        sorted_population = [x for _, x in sorted(zip(combined_fitness_values, combined_population), reverse=True)]
        
        # Keep the best two individuals from the sorted population as elites
        elites = sorted_population[:2]
        
        # Replace the worst two individuals in the sorted population with the elites
        sorted_population[-2:] = elites
        
        # Replace the old population with the sorted population
        population = sorted_population
        
        # Evaluate the new population
        fitness_values = [fitness(individual) for individual in population]
        best_fitness = max(fitness_values)
        best_hist.append(best_fitness)
        avg_hist.append(np.mean(fitness_values))
    
    return population, best_hist, avg_hist

In [279]:
for i in range(10):
    # Set a different random seed for each run
    random_seed = i
    
    # Run the genetic algorithm with the specified parameters and random seed
    population, best_hist, avg_hist = genetic_algorithm(pop_size=100, num_generations=50, chrom_length=10, p_cross=0.8, p_mut=0.1, random_seed=random_seed)
    
    # Print the best fitness value and the final population for this run
    print("Run {}: Best fitness = {}".format(i+1, max(best_hist)))
    print("Final population:")
    for individual in population:
        individual

TypeError: genetic_algorithm() got an unexpected keyword argument 'random_seed'